apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-demo-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.service.name }}
            port:
              number: {{ .Values.backend.service.targetPort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.service.name }}
            port:
              number: {{ .Values.frontend.service.targetPort }}
