replicaCount: 1
autoscaling:
  enabled: false

backend:
  name: backend
  group: api
  image:
    repository: docker.io/jvikstedt/gke-demo-app
    pullPolicy: IfNotPresent
    tag: "0.1"
  service:
    type: ClusterIP
    port: 3000
